### ISSUE TITLE
[Bug Report]Carousel组件 存在1px误差 transform: translate3d(-1px, 0px, 0px)

### ISSUE THREAD

**Issue by crank220** [view-design/ViewUI#244]
### Environment
官网

### Reproduction link
[https://www.iviewui.com/components/carousel#ZDQH](https://www.iviewui.com/components/carousel#ZDQH)

### Steps to reproduce
ransform: translate3d(-1px, 0px, 0px)

### What is expected?
ransform: translate3d(0px, 0px, 0px)

### What is actually happening?
ransform: translate3d(-1px, 0px, 0px)

**Comment by fengcms** [comment]
在官方没有修复的情况下，可以用下面这段CSS修复该问题 @crank220 
```css
.ivu-carousel-track + .ivu-carousel-track {
   margin-left: 1px;
}
```
