### ISSUE TITLE
table 嵌套Select,Select展开状态时Option列表不显示

### ISSUE THREAD

**Issue by changeforyou** [view-design/ViewUI#439]
table 嵌套Select,Select展开状态时Option列表不显示

**Comment by changeforyou** [comment]
4.0.0版本

**Comment by klren0312** [comment]
只能先这么操作了
```css
.ivu-table-wrapper {
  overflow: visible;
}
```
